---
- name: Install Minikube on Ubuntu
  hosts: localhost
  become: yes

  tasks:
    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

